// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('./../views/pages/about/components/card.vue')['default']
    Commands: typeof import('./../views/pages/home/components/commands.vue')['default']
    Contact: typeof import('./../views/components/contact.vue')['default']
    Coworks: typeof import('./../views/pages/home/components/coworks.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Galleria: typeof import('primevue/galleria')['default']
    Github: typeof import('./../views/components/github.vue')['default']
    Image: typeof import('primevue/image')['default']
    Images: typeof import('./../views/pages/home/components/images.vue')['default']
    Projects: typeof import('./../views/pages/projects/components/projects.vue')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Tag: typeof import('primevue/tag')['default']
    TheHeader: typeof import('./../views/components/TheHeader.vue')['default']
  }
}
